// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TcQezdJ7U8iYzHlgk8SqQYMTGw8vsnY',
    appId: '1:620753246336:web:2e6bbd7abae5b37157ae65',
    messagingSenderId: '620753246336',
    projectId: 'course-compass-f9bdd',
    authDomain: 'course-compass-f9bdd.firebaseapp.com',
    storageBucket: 'course-compass-f9bdd.appspot.com',
    measurementId: 'G-E2QJM6LD54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KWnEM4bUQyYWcjQBDYLWZjb36e5F8Ss',
    appId: '1:620753246336:android:5cfe3166b43c3ddc57ae65',
    messagingSenderId: '620753246336',
    projectId: 'course-compass-f9bdd',
    storageBucket: 'course-compass-f9bdd.appspot.com',
  );
}
